# Generated by Django 5.1.7 on 2025-03-14 07:09

import django.db.models.deletion
import django.utils.timezone
import photos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[photos.models.validate_name_length], verbose_name='Kép neve')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Kép')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Feltöltés dátuma')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Feltöltő')),
            ],
            options={
                'verbose_name': 'Fénykép',
                'verbose_name_plural': 'Fényképek',
                'ordering': ['-upload_date'],
            },
        ),
    ]
