kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"postgresql"}]'
    app.openshift.io/route-disabled: "false"
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: "https://github.com/Nemes2000/photoalbum.git"
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: "563411563"
  name: photo-album
  uid: 31cf7788-2ade-4214-91bd-88fbce176b6e
  creationTimestamp: "2025-03-24T16:32:20Z"
  generation: 39
  managedFields:
    - manager: member-operator
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: "2025-03-26T20:43:36Z"
      fieldsType: FieldsV1
      fieldsV1:
        "f:spec":
          "f:replicas": {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: "2025-03-29T09:07:19Z"
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:annotations":
            .: {}
            "f:app.openshift.io/connects-to": {}
            "f:app.openshift.io/route-disabled": {}
            "f:app.openshift.io/vcs-ref": {}
            "f:app.openshift.io/vcs-uri": {}
            "f:openshift.io/generated-by": {}
          "f:labels":
            .: {}
            "f:app": {}
            "f:app.kubernetes.io/component": {}
            "f:app.kubernetes.io/instance": {}
            "f:app.kubernetes.io/name": {}
            "f:app.kubernetes.io/part-of": {}
            "f:app.openshift.io/runtime": {}
            "f:app.openshift.io/runtime-version": {}
        "f:spec":
          "f:selector":
            .: {}
            "f:app": {}
            "f:deploymentconfig": {}
          "f:strategy":
            "f:activeDeadlineSeconds": {}
            "f:rollingParams":
              .: {}
              "f:intervalSeconds": {}
              "f:maxSurge": {}
              "f:maxUnavailable": {}
              "f:timeoutSeconds": {}
              "f:updatePeriodSeconds": {}
            "f:type": {}
          "f:template":
            .: {}
            "f:metadata":
              .: {}
              "f:creationTimestamp": {}
              "f:labels":
                .: {}
                "f:app": {}
                "f:deploymentconfig": {}
            "f:spec":
              .: {}
              "f:containers":
                .: {}
                'k:{"name":"photo-album"}':
                  .: {}
                  "f:imagePullPolicy": {}
                  "f:name": {}
                  "f:ports":
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      "f:containerPort": {}
                      "f:protocol": {}
                  "f:resources": {}
                  "f:terminationMessagePath": {}
                  "f:terminationMessagePolicy": {}
                  "f:volumeMounts":
                    .: {}
                    'k:{"mountPath":"/opt/app-root/src/media"}':
                      .: {}
                      "f:mountPath": {}
                      "f:name": {}
              "f:dnsPolicy": {}
              "f:restartPolicy": {}
              "f:schedulerName": {}
              "f:securityContext": {}
              "f:terminationGracePeriodSeconds": {}
              "f:volumes":
                .: {}
                'k:{"name":"mypd"}':
                  .: {}
                  "f:name": {}
                  "f:persistentVolumeClaim":
                    .: {}
                    "f:claimName": {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: "2025-03-29T10:47:46Z"
      fieldsType: FieldsV1
      fieldsV1:
        "f:spec":
          "f:template":
            "f:spec":
              "f:containers":
                'k:{"name":"photo-album"}':
                  "f:image": {}
          "f:triggers": {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: "2025-03-30T08:52:02Z"
      fieldsType: FieldsV1
      fieldsV1:
        "f:status":
          "f:availableReplicas": {}
          "f:conditions":
            .: {}
            'k:{"type":"Available"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:lastUpdateTime": {}
              "f:message": {}
              "f:status": {}
              "f:type": {}
            'k:{"type":"Progressing"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:lastUpdateTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
          "f:details":
            .: {}
            "f:causes": {}
            "f:message": {}
          "f:latestVersion": {}
          "f:observedGeneration": {}
          "f:replicas": {}
          "f:unavailableReplicas": {}
          "f:updatedReplicas": {}
      subresource: status
  namespace: nemes2000-dev
  labels:
    app: photo-album
    app.kubernetes.io/component: photo-album
    app.kubernetes.io/instance: photo-album
    app.kubernetes.io/name: photo-album
    app.kubernetes.io/part-of: photo-album
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.12-ubi8
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - photo-album
        from:
          kind: ImageStreamTag
          namespace: nemes2000-dev
          name: "photo-album:latest"
        lastTriggeredImage: "image-registry.openshift-image-registry.svc:5000/nemes2000-dev/photo-album@sha256:e761e5b5c837f9c04cc0bb32ec114cdebbb624c1e4a938ab692c09cff4ad6710"
    - type: ConfigChange
  replicas: 0
  revisionHistoryLimit: 10
  test: false
  selector:
    app: photo-album
    deploymentconfig: photo-album
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: photo-album
        deploymentconfig: photo-album
    spec:
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: photostorage
      containers:
        - name: photo-album
          image: "image-registry.openshift-image-registry.svc:5000/nemes2000-dev/photo-album@sha256:e761e5b5c837f9c04cc0bb32ec114cdebbb624c1e4a938ab692c09cff4ad6710"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: mypd
              mountPath: /opt/app-root/src/media
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  latestVersion: 23
  observedGeneration: 39
  replicas: 0
  updatedReplicas: 0
  availableReplicas: 0
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: DockerImage
            name: "image-registry.openshift-image-registry.svc:5000/nemes2000-dev/photo-album@sha256:e761e5b5c837f9c04cc0bb32ec114cdebbb624c1e4a938ab692c09cff4ad6710"
  conditions:
    - type: Progressing
      status: "True"
      lastUpdateTime: "2025-03-29T10:47:55Z"
      lastTransitionTime: "2025-03-29T10:47:51Z"
      reason: NewReplicationControllerAvailable
      message: replication controller "photo-album-23" successfully rolled out
    - type: Available
      status: "False"
      lastUpdateTime: "2025-03-30T08:52:02Z"
      lastTransitionTime: "2025-03-30T08:52:02Z"
      message: Deployment config does not have minimum availability.
